# Generated by Django 4.1.4 on 2022-12-12 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_post_thread_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=59)),
                ('name', models.CharField(max_length=256)),
                ('mimetype', models.CharField(max_length=36)),
                ('size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('height', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('length', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reply',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='messaging.board'),
        ),
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(to='messaging.attachment'),
        ),
    ]
