# Generated by Django 4.1.4 on 2023-01-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_attachment_thread_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='target',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='messaging.reply'),
        ),
    ]
