# Generated by Django 4.1.4 on 2022-12-20 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_attachment_alter_reply_origin_alter_thread_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 20, 19, 13, 48, 497279, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
