# Generated by Django 4.1.4 on 2023-01-03 07:20

from django.db import migrations, models
import django.db.models.deletion


def set_previews_to_null(apps, _schema_editor) -> None:
    """ Set all previews to NULL to prevent IntegrityError """
    Attachment = apps.get_model('messaging', 'Attachment')
    for attachment in Attachment.objects.all():
        attachment.preview = None
        attachment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_attachment_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=59)),
                ('mimetype', models.CharField(max_length=36)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
            ],
        ),
        migrations.RunPython(set_previews_to_null),
        migrations.AlterField(
            model_name='attachment',
            name='preview',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.preview'),
        ),
    ]
