# Generated by Django 4.1.5 on 2023-01-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_preview_alter_attachment_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='length',
        ),
        migrations.AddField(
            model_name='attachment',
            name='duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
