# Generated by Django 4.1.5 on 2023-01-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_remove_attachment_length_attachment_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='target',
        ),
        migrations.AddField(
            model_name='reply',
            name='targets',
            field=models.ManyToManyField(to='messaging.reply'),
        ),
    ]
