# Generated by Django 4.1.5 on 2023-01-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_remove_reply_target_reply_targets'),
    ]

    operations = [
        migrations.RenameField('Reply', 'targets', 'connections'),
    ]
